### PR TITLE
improvement: add `register_parent/1` to `Appsignal.Tracer`

### PR DESCRIPTION
**Pull request by zachdaniel**
Need something like this for `ash_appsignal` which starts processes for you.

See #895 for context.

### CODE REVIEW

**Comment by zachdaniel** [comment]
Not sure if I necessarily need to follow those instructions up there ^. Seems weird for me to explicitly tag reviewers, for example, as an outside contributor. Some guidance would be appreciated :)

**Comment by unflxw** [comment]
@zachdaniel Ah, no, don't worry about that. Adding us as reviewers is good, so we don't forget about it. Any other changes that need to be done, like the changeset, we'll likely do them ourselves.

(The bot is also, it seems, confused about whose PR this is, and keeps editing the message mentioning different people 😅)

Re: naming (everyone's favorite topic) I'd go with `register_current/1`, as the span that's being registered is the current span. But anything is fine, I think it's likely we'll `@doc false` this for the time being.

**Review by jeffkreeftmeijer — APPROVED** [review]
Looks good! Agreed with @unflxw, could you update the name for the added function and `@doc false` it?

**Comment by unflxw** [comment]
Continuing work at #898; closing.

**Pull request closed without merging**
