### PR TITLE
Use httpc, drop HTTPoison dependency

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**

### CODE REVIEW

**Comment by tombruijn** [comment]
I think we need to configure httpc a bit more for SSL cert verification. Was reading up on httpc usage and found this post: https://blog.voltone.net/post/7 see httpc section.

We probably should also use the ca_cert_file config option here if it is set.

**Comment by tombruijn** [comment]
Well.. I have broken it some more.

```
$ mix appsignal.diagnose
16:13:31.227 [error] SSL: :certify: ssl_handshake.erl:420:Fatal error: certificate unknown - failed_to_decode_certificate

{:failed_connect,
 [{:to_address, {'push.appsignal.com', 443}},
  {:inet, [:inet], {:tls_alert, 'certificate unknown'}}]}
```

Not sure why I'm getting this error. Help is appreciated

Although I'm wondering if it's worth the trouble switching to httpc if this takes up too much time and code to get this to work.

**Comment by wesoudshoorn** [comment]
Discuss in Roadmap Q3

**Comment by tombruijn** [comment]
Not important enough for now. The issue hasn't happened in a while.

**Pull request closed without merging**
