### PR TITLE
Add script to run all tests locally

### PR DESCRIPTION
**Pull request by jvanbaarsen**
This includes all the linting as well. Might prevent useless CI waiting.

### CODE REVIEW

**Comment by tombruijn** [comment]
Can we also run this script on travis then? If it's running all the tests as well

**Comment by jvanbaarsen** [comment]
@tombruijn 	In that case I probably need to change it a bit. Since we do all type of extra checks on CI. I'll move this to WIP for now.

**Comment by jvanbaarsen** [comment]
I updated everything, and added it to Travis. @jeffkreeftmeijer Can you re-review?

**Comment by jvanbaarsen** [comment]
@jeffkreeftmeijer Sounds good, do we also want to do that for Credo?

**Comment by jeffkreeftmeijer** [comment]
Yes, we can run both credo and the formatter on 1.8 only.

**Pull request merged**
