### PR TITLE
Store action names in registry to set them after the request is done, unless overridden

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
By storing the actions in the TransactionRegistry, we can revert back to setting the action name after the request is done. This will fix issues we're seeing where the action names for umbrella apps aren't properly set.

### CODE REVIEW

**Comment by tombruijn** [comment]
@jeffkreeftmeijer are you still working on this to fix the discussed issues or are fixes included for thos?
If not, let's move it to WIP.

**Comment by jeffkreeftmeijer** [comment]
Moved back to WIP.

**Comment by tombruijn** [comment]
Waiting for feedback or a way to reproduce it.
Moving to waiting.

**Comment by tombruijn** [comment]
We haven't received any feedback. We're not sure if it will fix the issue, so we're closing it for now.

**Pull request closed without merging**
