### PR TITLE
Make sure to use hackney 1.16 and up on OTP 23

### LINKED ISSUE #562: Erlang/OTP 23.0 Compatibility
## Describe the bug

Hi, Erlang/OTP 23.0 was just released, and Elixir 1.10.3 seems to be compatible: https://twitter.com/elixirlang/status/1260556559165292544

However, when deploying my app, I'm getting an error from AppSignal:
```shell
warning: Error loading NIF (Is your operating system (x86_64-pc-linux-musl) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
Failed to load NIF library: 'Error loading shared library /app/lib/appsignal-1.13.1/priv/appsignal_extension.so: No such file or directory'
   (appsignal 1.13.1) lib/appsignal/nif.ex:48: Appsignal.Nif.init/0
   anonymous fn/1 in :init.run_on_load_handlers/2
```

I've checked the docs mentioned in the error message, and `Alpine 1.10.3` should be supported.

When building, `mix deps.compile` fails (but doesn't abort), yielding the following:

```shell
AppSignal installation failed: {:error, {:error, {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}}}}
```

Looks like this could be due to the removal of SSL 3?
See https://www.erlang.org/news/140
> SSL:
>    Support for SSL 3.0 is completely removed.
>    TLS 1.3 is added to the list of default supported versions.

## To Reproduce

- Using AppSignal for Elixir package version 1.13.1
- In my app using framework/library phoenix version 1.5.1
- Using docker image `hexpm/elixir:1.10.3-erlang-23.0-alpine-3.11.3`
  - With the image `hexpm/elixir:1.10.3-erlang-22.3-alpine-3.11.3` all works fine.

I'm aware that Erlang/OTP 23 is brand new and contains quite a few breaking changes, so no sweat :)

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Closes #562.

### CODE REVIEW

**Comment by tombruijn** [comment]
The current selector doesn't prevent users from using version 1.16, right? Is this for the CI builds or just to ensure apps don't use an incompatible version?

Does the last work if we push from a lower version than OTP 23, because we push the dependencies definition to hex on release.

**Comment by jeffkreeftmeijer** [comment]
These are the dependencies for the library, so this patch would force hackney ~> 1.16 on machines running OTP 23 or higher. That's a good idea, because earlier versions of hackney don't support OTP 23 and throw ssl errors when you try to do a request.

The question we'll need to answer is; are we okay with dependency mismatches when somebody installs AppSignal in their app which has an onder version of hackney locked in? If so, we can force hackney 1.16 on OTP 23, since it's always broken on earlier versions, and it breaks our installation.

**Comment by tombruijn** [comment]
> These are the dependencies for the library, so this patch would force hackney ~> 1.16 on machines running OTP 23 or higher. 

I thought mix/hex would only install the dependency listed on https://hex.pm/packages/appsignal ? So if we push from one of our machines with OTP >= 23, hex would register it as `hackney ~> 1.16`.
Then when pulled for dependency resolution it would also use `hackney ~> 1.16` as matcher regardless of local OTP version.

Or does mix/hex download the AppSignal `mix.exs` first (of the latest release?), and then figure out the dependency versions?

> The question we'll need to answer is; are we okay with dependency mismatches when somebody installs AppSignal in their app which has an onder version of hackney locked in?

From my understanding hackney < 1.16 doesn't work on OTP 23 at all for requests using SSL 3?

We're still compatible on older versions, and we don't require users to upgrade. So when users run into this issue they should upgrade hackney, but it's not required for all scenarios.

If we want to prevent older hackney versions from being installed with AppSignal we should add `~> 1.16` as the version lock for all OTPs and release it as a minor version. I'm okay with that.

**Comment by jeffkreeftmeijer** [comment]
Double-checked, you're right. Closing this one.

**Pull request closed without merging**
