### PR TITLE
Add :hackney to :applications

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Fixes a problem where the diagnose command failed to validate push API
keys via the API, because the :hackney application wasn't loaded in
distillery releases.

This patch doesn't switch to :extra_applications to keep compatibilty
with older Elixir versions.

### CODE REVIEW

**Comment by tombruijn** [comment]
```
Diagnostics report
  Do you want to send this diagnostics report to AppSignal?
  If you share this diagnostics report you will be given
  a support token you can use to refer to your diagnotics
  report when you contact us at support@appsignal.com

  Send diagnostics report to AppSignal? (Y/n): y

  Transmitting diagnostics report
{"init terminating in do_boot",{undef,[{'Elixir.Poison','encode!',[#{diagnose=>#{config=>#{active=>true,ca_file_path=><<"/app/lib/appsignal-1.8.0/priv/cacert.pem">>,debug=>true,diagnose_endpoint=><<"https://appsignal.com/diag">>,dns_servers=>[],enable_host_metrics=>true,endpoint=><<"https://push.appsignal.com">>,env=>prod,files_world_accessible=>true,filter_parameters=>[],filter_session_data=>[],ignore_actions=>[],ignore_errors=>[],ignore_namespaces=>[],log=><<"file">>,name=><<"appsignal-plug-example">>,push_api_key=><<"4ba6f264-d8e9-4e41-853e-15600e39e8b6">>,request_headers=>[<<"accept">>,<<"accept-charset">>,<<"accept-encoding">>,<<"accept-language">>,<<"cache-control">>,<<"connection">>,<<"content-length">>,<<"path-info">>,<<"range">>,<<"request-method">>,<<"request-uri">>,<<"server-name">>,<<"server-port">>,<<"server-protocol">>],send_params=>true,skip_session_data=>false,valid=>true},host=>#{architecture=><<"x86_64-pc-linux-musl">>,heroku=>false,language_version=><<"1.7.3">>,otp_version=><<"21">>,root=>true,running_in_container=>false},library=>#{agent_architecture=><<"x86_64-linux-musl">>,agent_version=><<"7859eb4">>,extension_loaded=>false,language=><<"elixir">>,package_version=><<"1.8.0">>},logs=>#{'install.log'=>#{content=>[<<"[2018-10-08 14:32:33.202900Z] Error loading NIF (Is your operating system (x86_64-pc-linux-musl) supported? Please check http://docs.appsignal.com/support/operating-systems.html):">>,<<"Failed to load NIF library: 'Error loading shared library libgcc_s.so.1: No such file or directory (needed by /app/lib/appsignal-1.8.0/priv/appsignal_extension.so)'">>,<<>>,<<>>],exists=>true,path=><<"/app/lib/appsignal-1.8.0/install.log">>}},paths=>#{log_dir_path=>#{configured=>true,exists=>true,ownership=>#{uid=>0},path=><<"/tmp">>,writable=>true},log_file_path=>#{configured=>true,exists=>false,path=><<"/tmp/appsignal.log">>,writable=>false}},process=>#{uid=>0},validation=>#{push_api_key=><<"valid">>}}}],[]},{'Elixir.Appsignal.Diagnose.Report',send,2,[{file,"lib/appsignal/diagnose/report.ex"},{line,21}]},{'Elixir.Mix.Tasks.Appsignal.Diagnose',send_report_to_appsignal_if_agreed_upon,2,[{file,"lib/mix/tasks/appsignal.diagnose.ex"},{line,184}]},{appsignal_tasks,diagnose,0,[{file,"lib/appsignal/utils/tasks.ex"},{line,3}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{Elixir.Poison,encode!,[],[]},{Elixir.Appsignal.Diagnose.Report,send,2,[{_},{_}]},{Elixir.Mix.Tasks.Appsignal.Diagnose,send_report_to_appsignal_if_agreed_upon,2,[{

Crash dump is being written to: erl_crash.dump...done
```

I'm guessing poison also needs to be added to the apps?

**Comment by tombruijn** [comment]
```
Diagnostics report
  Do you want to send this diagnostics report to AppSignal?
  If you share this diagnostics report you will be given
  a support token you can use to refer to your diagnotics
  report when you contact us at support@appsignal.com

  Send diagnostics report to AppSignal? (Y/n): y

  Transmitting diagnostics report
{"init terminating in do_boot",{undef,[{'Elixir.Poison','encode!',[#{diagnose=>#{config=>#{active=>true,ca_file_path=><<"/app/lib/appsignal-1.8.0/priv/cacert.pem">>,debug=>true,diagnose_endpoint=><<"https://appsignal.com/diag">>,dns_servers=>[],enable_host_metrics=>true,endpoint=><<"https://push.appsignal.com">>,env=>prod,files_world_accessible=>true,filter_parameters=>[],filter_session_data=>[],ignore_actions=>[],ignore_errors=>[],ignore_namespaces=>[],log=><<"file">>,name=><<"appsignal-plug-example">>,push_api_key=><<"">>,request_headers=>[<<"accept">>,<<"accept-charset">>,<<"accept-encoding">>,<<"accept-language">>,<<"cache-control">>,<<"connection">>,<<"content-length">>,<<"path-info">>,<<"range">>,<<"request-method">>,<<"request-uri">>,<<"server-name">>,<<"server-port">>,<<"server-protocol">>],send_params=>true,skip_session_data=>false,valid=>true},host=>#{architecture=><<"x86_64-pc-linux-musl">>,heroku=>false,language_version=><<"1.7.3">>,otp_version=><<"21">>,root=>true,running_in_container=>false},library=>#{agent_architecture=><<"x86_64-linux-musl">>,agent_version=><<"7859eb4">>,extension_loaded=>false,language=><<"elixir">>,package_version=><<"1.8.0">>},logs=>#{'install.log'=>#{content=>[<<"[2018-10-08 14:32:33.202900Z] Error loading NIF (Is your operating system (x86_64-pc-linux-musl) supported? Please check http://docs.appsignal.com/support/operating-systems.html):">>,<<"Failed to load NIF library: 'Error loading shared library libgcc_s.so.1: No such file or directory (needed by /app/lib/appsignal-1.8.0/priv/appsignal_extension.so)'">>,<<>>,<<>>],exists=>true,path=><<"/app/lib/appsignal-1.8.0/install.log">>}},paths=>#{log_dir_path=>#{configured=>true,exists=>true,ownership=>#{uid=>0},path=><<"/tmp">>,writable=>true},log_file_path=>#{configured=>true,exists=>false,path=><<"/tmp/appsignal.log">>,writable=>false}},process=>#{uid=>0},validation=>#{push_api_key=><<"valid">>}}}],[]},{'Elixir.Appsignal.Diagnose.Report',send,2,[{file,"lib/appsignal/diagnose/report.ex"},{line,21}]},{'Elixir.Mix.Tasks.Appsignal.Diagnose',send_report_to_appsignal_if_agreed_upon,2,[{file,"lib/mix/tasks/appsignal.diagnose.ex"},{line,184}]},{appsignal_tasks,diagnose,0,[{file,"lib/appsignal/utils/tasks.ex"},{line,3}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{Elixir.Poison,encode!,[],[]},{Elixir.Appsignal.Diagnose.Report,send,2,[{_},{_}]},{Elixir.Mix.Tasks.Appsignal.Diagnose,send_report_to_appsignal_if_agreed_upon,2,[{

Crash dump is being written to: erl_crash.dump...done
```

I'm guessing poison also needs to be added to the apps?
(Ignore the other errors, it's part of the issue I'm debugging)

**Comment by jeffkreeftmeijer** [comment]
Haven't seen that one. Is that an Elixir-only app without any implicit dependencies on Poison (so not a Phoenix application)?

**Comment by tombruijn** [comment]
I tested this in a Plug app.

**Comment by jeffkreeftmeijer** [comment]
That explains it (and why it didn't work in my Phoenix app). There's a fix in https://github.com/appsignal/appsignal-elixir/pull/404.

**Pull request merged**
