### PR TITLE
Extract ETS and Receiver logic from TransactionRegistry

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
This pull request contains @BenMorganIO's changes, submitted in https://github.com/appsignal/appsignal-elixir/pull/504. I'm opening this one here as the original included some unrelated fixes to the test suite and a benchmark for the Registry, which are already merged.

I've also removed the style changes from the original pull request's commits, to make this easier to review and push out as a new release. We should decide on a coding and documentation style, but we're definitely willing to clean the codebase up in this regard.

Ben's functionality remains unchanged and has been working great in my testing. @tombruijn and @jvanbaarsen could you try this branch in your apps, to make sure everything still works as you'd expect? I haven't seen it fail, but one place this patch might have an effect on would be error reporting from the Plug include. We need to make sure errors from Plug and Phoenix apps don't get reported twice. Please ping if you need help testing this out.

@BenMorganIO thanks once more for this patch! After we're done reviewing, we'll cut a beta that includes this patch to have users test it before the final release.

### CODE REVIEW

**Comment by tombruijn** [comment]
@jeffkreeftmeijer maybe you can talk me and @jvanbaarsen through the changes that were made in a call?

**Comment by BenMorganIO** [comment]
I can help try and explain it if it's no problem.

**Comment by jeffkreeftmeijer** [comment]
We've decided that I should write an overview of the changes instead of having a call about this to keep the process a little more async. @BenMorganIO, thanks for your offer to help out, are you missing anything in the overview below?

@tombruijn @jvanbaarsen, behold:

Before this patch, the `TransactionRegistry` was in charge of all operations concerning the registering and finding transactions for any process with an AppSignal Transaction, as well as removing rows from the ETS table if they were no longer needed.

Instead of handling all of the work in one process, Ben’s patch splits the TransactionRegistry up into three parts; `Transaction.Receiver`, `Transaction.ETS` and what’s left of `TransactionRegistry`.

## `Transaction.ETS`

This patch moves the ETS table logic to its own module to reduce the responsibilities of the registry, and to a separate process, which is supervised on its own. 

## `Transaction.Receiver`

The newly added Receiver takes care of monitoring and demonitoring processes. We use process monitors to get notified when a process dies, so we can remove it from the ETS table automatically.

Process monitors work by waiting for a `:DOWN` message, which the TransactionRegistry used to handle, but is now handled by the Receiver. Because it runs in a separate process, it can block without affecting the rest of the registry.

## `TransactionRegistry`

Since the `TransactionRegistry` isn’t responsible for talking to ETS and receiving monitor messages, what’s left is an API for the rest of the integration to communicate with. 

## Results

The result of splitting these parts up is that responsibilities are now more clearly split, and that the Registry is more performant, because blocking operations are moved out of the main GenServer and into their own processes. 

I haven’t been able to find any regressions, but the most likely place for them would be in the process ignoring. In the `Appsignal.Plug`, we ignore any processes after sending an error to make sure the same error doesn’t get caught by the background error handler again. This can be tested by raising errors from a Phoenix app, like my [example](https://github.com/jeffkreeftmeijer/appsignal-phoenix-example), which has a controller with actions that raise exceptions to test this.

**Comment by hosh** [comment]
Been looking forward to this!

**Pull request merged**
