### PR TITLE
Ignore unhandled info, code_change and terminate to actually behave as a :gen_event

### LINKED ISSUE #590: Undefined handle_info warnings
Hi there, i've upgraded to 2.0 and getting tons of this in my logs:

```
** [warning] Undefined handle_info in 'Elixir.Appsignal.Error.Backend'
** Unhandled message: {io_reply,#Ref<0.3002323228.2069889025.15981>,ok}
```
Not sure from where it coming but after some investigate i've find out that Appsignal.Error.Backend needs to ignore some messages to behave like :gen_event.

### Environment
- appsignal_phoenix, "~> 2.0.0"
- phoenix, "~> 1.5.6"
- elixir 1.11.2

I will send fix for this soon.

### PR DESCRIPTION
**Pull request by anronin**
Closes #590

### CODE REVIEW

**Comment by jeffkreeftmeijer** [comment]
Hey @anronin,

Thanks for diving into this. The patch looks great, but we’d like to add a test here to make sure the added code is checked on CI. If you have time, could you try adding a test that calls each of these functions? If not, I’ll take a look at this next week before releasing 2.0.1.

Thanks again!
-- Jeff

**Comment by anronin** [comment]
hi @jeffkreeftmeijer! sure, tests was added, should i fix dialyzer warning for `ok?/1`?

**Comment by jeffkreeftmeijer** [comment]
Hey @anronin,

Thanks! This looks perfect! It’d be great if you can also look at that Dialyzer issue, but it’s on my list today, so I’ll get to it myself before releasing 2.0.1. Thanks again for your help!

Best,
-- Jeff

**Comment by jeffkreeftmeijer** [comment]
I've added a fix to your work for the dialyzer issue in #594. Could you check the `unhandled-messages` branch if you have time? I’ll close this one, so let’s continue in the new PR.

**Pull request closed without merging**
