### PR TITLE
Run Mix format on the entire project

### LINKED ISSUE #389: Adding mix format
I was checking out the project, and I noticed that it does not yet make use of Elixir formatter.

When I tried adding it and running it I noticed a ton of files changed, so before I actually submit such a PR I wanted to check in if you would be open for adding this?

The benefit is that it will make sure the code is "community standard". You can hook it up to your editor ( I have it hooked up for vim), to format the code on save. The downside is that it will have a one-off reviewing cost that can be quite high.

To add an extra layer of security, you can also add it to your CI.

In case you want to read more about it, you can do so here: https://hashrocket.com/blog/posts/format-your-elixir-code-now

Let me know if you would be interested in such a change.

### PR DESCRIPTION
**Pull request by jvanbaarsen**
This runs the Mix format command on the entire codebase, as discussed in

The PR is really massive, but it seems like all the tests are passing.

If this is a change you would rather do by yourselve, then you can just
close this one :-)

Fixes #389

### CODE REVIEW

**Comment by tombruijn** [comment]
I'll have to look at the changes still, but let's plan to merge this after the 1.8 package release of this week.

**Comment by tombruijn** [comment]
Is there also a way to add this to the build so it fails if there's a violation in the styleguide?

**Comment by jeffkreeftmeijer** [comment]
Yes. `mix format --check-formatted --dry-run`

**Comment by tombruijn** [comment]
yay conflicting files after 100f3dd6aa9c53d02cb8863b1bb3907a1ffc414b

**Comment by jeffkreeftmeijer** [comment]
yay fixed!

**Comment by jvanbaarsen** [comment]
@tombruijn If you want I can add that step to the travis buildfile?

**Comment by tombruijn** [comment]
Hi @jvanbaarsen 👋 Will you add the step to the TravisCI build step? We want to merge this PR next week.

**Comment by jvanbaarsen** [comment]
@tombruijn Yes will do! Sorry about the delay, got a bit busy :)

**Comment by jvanbaarsen** [comment]
@tombruijn Interesting, one thing that I didn't think about is that the gem also has tests for Elixir < 1.6.6. So those test suites don't support `mix format`.

What we could do is make a script file that runs the formatter. That script can then check if the test are running against > 1.6.

Let me know what you think :)

**Comment by jvanbaarsen** [comment]
@tombruijn I went ahead and wrote a little wrapper script for the formatter. It checks if the Elixir version on Travis is 1.6.6 or above, if that is the case it will run the formatter.

**Comment by tombruijn** [comment]
@jeffkreeftmeijer can you take a look at the latest changes and update your review?

**Comment by tombruijn** [comment]
Thanks @jvanbaarsen for the PR!

**Pull request merged**
