### PR TITLE
Add LiveView support

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Based on @isavita's pull request in #548, this pull request continues work to finish the work on adding LiveView support, and is drafted to get CI to run tests.

### CODE REVIEW

**Comment by jeffkreeftmeijer** [comment]
Hey @isavita,

Let's continue here, as I've done some work to get this ready to be merged. I've made sure we don't add the LiveView dependency to apps running on an Elixir version below 1.7, and I've added regression tests for the `Appsignal.Phoenix.LiveView` module. 

However, I'm unsure about the decorators. Since LiveView events can be called to in multiple ways, it seems like it'd be difficult to have decorators that work for all cases. For example, using `send` and `handle_info` with the live_view_event decorator currently breaks as there's no function clause without parameters.

```
@decorate live_view_event
def handle_info(:tick, socket) do
```

Also, in the current implementation, the event name extraction fails if it's not an atom;

```
@decorate live_view_event
def handle_info(name, socket) do
```

Instead of trying to get this perfect, I'm thinking of dropping the decorators and only adding the instrumentation helpers in Appsignal.Phoenix.LiveView, to be used like our [channel instrumentation helpers](https://docs.appsignal.com/elixir/instrumentation/instrumentation.html#instrumentation-helper-functions).

**Comment by isavita** [comment]
Thank you @jeffkreeftmeijer !
The `live_view_event` was for [handle_event](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:handle_event/3). It is always binary. Probably better name will be `live_view_handle_event`.
I agree for the decorators for that when in the path to have them explicit, but name this one badly.
The [handle_info](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:handle_info/2) can be `term`. I would imagine to add `live_view_handle_info` for it. 

Live view has 5 [callbacks](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#callbacks).

I was imagining having explicit decorator for each.
```elixir
@decorate mount
def mount(:tick, socket) do
```
```elixir
@decorate live_view_handle_event
def handle_event(:tick, socket) do
```
```elixir
@decorate live_view_handle_info
def handle_info(:tick, socket) do
```

**Comment by jeffkreeftmeijer** [comment]
Hey @isavita,

Thanks once again for your work on this patch. We've just merged LiveView support into develop and released 1.13.0-beta.1 with the instrumentation helpers. We'll look into adding decorator-like helpers in a future version of our integration, but we wanted to ship this to our users so they can start instrumenting their live views, and gain some feedback on the implementation.

For everyone reading along; please try the beta and let us know how the helpers work for you. We'll work on adding documentation and will release 1.13.0 after some more testing on our side.

Thanks!

**Comment by sergiotapia** [comment]
Where did this end up @jeffkreeftmeijer ? I don't see any of the liveview decorators on latest. https://github.com/appsignal/appsignal-elixir/blob/24fce5d05f1381f83726d3d5edbfac8ba5fca0d2/lib/appsignal/instrumentation/decorators.ex

Appreciate the help

**Comment by tombruijn** [comment]
Hi @sergiotapia, we moved the live view integration to the [appsignal_phoenix](https://hex.pm/packages/appsignal_phoenix) package, in version 2.0 of the appsignal-elixir package.

**Comment by sergiotapia** [comment]
Thanks @tombruijn my code works and looks like this:

```
@impl true
  def mount(_params, _session, socket) do
    live_view_action(__MODULE__, "mount", socket, fn ->
      changeset = Leads.change_waitlist(%Waitlist{})

      socket =
        assign(socket,
          changeset: changeset,
          waitlist_submitted: get_connect_params(socket)["waitlist_submitted"]
        )

      {:ok, socket, layout: {GamingWeb.LayoutView, "live_no_navbar.html"}}
    end)
  end
```

Is it left as an exercise for the reader to implement this as a tidier decorator?

**Comment by tombruijn** [comment]
We don't have decorators for this part of Phoenix unfortunately. We haven't found a better way to support it yet. We actually want to remove decorators entirely and replace it with something better, like macros. You can write your own macro for this as well. Please share yours if you write one.

**Comment by sergiotapia** [comment]
@tombruijn Thanks Tom, a better way to do this was proposed by Ben Wilson - use the new Liveview hooks. https://sergiotapia.com/integrating-appsignal-with-phoenix-liveview-tutorial

**Comment by tombruijn** [comment]
@sergiotapia that could be interesting! Thanks for writing the article!
I've created an issue for it here: https://github.com/appsignal/appsignal-elixir-phoenix/issues/37

**Comment by cblavier** [comment]
I'm using Phoenix LiveView telemetry events to instrument events & report errors with metadata: https://gist.github.com/cblavier/faaee0e3969de708737ed0e6c623d3dd

The issue now is that I get duplicate errors since they are also handled by the generic background reporter. Any idea how to handle this issue?

**Comment by cblavier** [comment]
@jeffkreeftmeijer if you have any idea how to tackle this issue (duplicate errors mentioned in my last post), I would be happy to open a PR on the appsignal-elixir-phoenix project

**Comment by jeffkreeftmeijer** [comment]
Hey @cblavier,

Something we do in the Plug instrumentation is ignoring the current pid when the error is caught there, so it’s ignored in the error handler using `Appsignal.Tracer.ignore/0`. Would something like that work for your use case?

https://github.com/appsignal/appsignal-elixir-plug/blob/263441640bc06d02c32843a289441ef570f4052c/lib/appsignal_plug.ex#L52-L62

**Comment by cblavier** [comment]
The Telemetry genserver I wrote is actually running in a different process so if I call `Tracer.ignore/0` I guess it won't ignore the correct pid (liveview's pid)

The other issue is that I'm not sure when I will receive the telemetry event (sometime before, sometime after the exception is actually catched by the liveview)

Is there a way to make appsignal merge bug reports based on some unique identifier? 
Or to get the same `span` used if I create a span with a specific pid?

**Comment by cblavier** [comment]
Ok I may have found something working, by using a new `Tracer.ignore/1` function that I use to ignore liveview's pid from my telemetry listener.
WDYT?

**Comment by cblavier** [comment]
The telemetry integration is now running perfectly for us in production. It's really valuable because of the extra context it contains when reporting bugs in LiveView callbacks.

Do you think it could be integrated in your codebase? 
If you give me some guidelines, I can open a PR

**Comment by cblavier** [comment]
I just noticed that using previous gist (telemetry server), I don't have a detailed breakdown of the LiveView event:

CleanShot 2022-02-22 at 10 20 49

Any clue of how I could improve this?

**Comment by cblavier** [comment]
Ok I figured it out and I now have detailed breakdown of LiveviewEvents. I updated my [gist](https://gist.github.com/cblavier/faaee0e3969de708737ed0e6c623d3dd)
@jeffkreeftmeijer do you think it deserves a PR?

**Comment by jeffkreeftmeijer** [comment]
Hey @cblavier,

Thanks for working on this! We have [a pull request open for auto-instrumenting LiveView events](https://github.com/appsignal/appsignal-elixir-phoenix/pull/40) right now, so we’re looking into that as well. The question now is how we’d want to support LiveView going forward. If we can do what we’re doing with LiveView now through `:telemetry` completely, that’d be my preference right now. However, I haven’t had time to properly dive into this. 

If it’s not too much work, could you throw your code in a pull request on appsignal-elixir-phoenix to continue the conversation there?

**Pull request merged**
